version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install flask
  build:
    commands:
      - echo "Build phase completed"
artifacts:
  files:
    - '**/*'
